# examples/basic_features.yaml
feature_a:
  description: "Raw feature A"
  data_type: "float"

feature_b:
  description: "Raw feature B"
  data_type: "float"

feature_c:
  description: "Derived feature C"
  data_type: "float"
  dependencies: ["feature_a", "feature_b"]
  transformation:
    sum_fn:
      _target_: feature_fabrica.transform.SumFn
      iterable: ["feature_a", "feature_b"]
    scale_feature:
      _target_: feature_fabrica.transform.ScaleFeature
      factor: 0.5
