# examples/basic_features.yaml
feature_a:
  description: "Raw feature A"
  data_type: "int32"
  group: "training"

feature_b:
  description: "Raw feature B"
  data_type: "float32"
  group: "training"
  transformation:
    scale_feature:
      _target_: feature_fabrica.transform.ScaleFeature
      factor: 2.

feature_d:
  description: "Derived feature D"
  data_type: "float32"
  group: "training"
  dependencies: ["feature_a"]
  transformation:
    sum_fn:
      _target_: feature_fabrica.transform.SumReduce
      iterable: [2, "feature_a"]
    multiply:
      _target_: feature_fabrica.transform.DivideTransform
      numerator: 2

feature_c:
  description: "Derived feature C"
  data_type: "float32"
  group: "training"
  dependencies: ["feature_a", "feature_b"]
  transformation:
    sum_fn:
      _target_: feature_fabrica.transform.SumReduce
      iterable: ["feature_a", "feature_b"]
    scale_feature:
      _target_: feature_fabrica.transform.ScaleFeature
      factor: 0.5

feature_e:
  description: "Raw feature E"
  data_type: "int32"
  group: "draft"
  transformation:
    upper:
      _target_: feature_fabrica.transform.ToUpper
    lower:
      _target_: feature_fabrica.transform.ToLower
    one_hot:
      _target_: feature_fabrica.transform.OneHotEncode
      categories: ["apple", "orange"]

feature_f:
  description: "Raw feature F"
  data_type: "str_"
  group: "target"
  transformation:
    strip:
      _target_: feature_fabrica.transform.Strip
