# examples/basic_features.yaml
feature_a:
  description: "Raw feature A"
  data_type: "int32"
  group: "training"

feature_b:
  description: "Raw feature B"
  data_type: "float32"
  group: "training"
  transformation:
    scale_feature:
      _target_: ().scale(factor=2)

feature_d:
  description: "Derived feature D"
  data_type: "float32"
  group: "training"
  dependencies: ["feature_a"]
  transformation:
    multiply:
      _target_: (feature_a).scale(factor=6)
    divide:
      _target_: ().divide(denominator=2)

feature_c:
  description: "Derived feature C"
  data_type: "float32"
  group: "training"
  dependencies: ["feature_a", "feature_b"]
  transformation:
    solve:
      _target_: (feature_a + feature_b) / 2

feature_e:
  description: "Raw feature E"
  data_type: "int32"
  group: "draft"
  transformation:
    _target_: ().upper().lower().one_hot(categories=['apple', 'orange'])

feature_f:
  description: "Raw feature F"
  data_type: "str_"
  group: "target"
  transformation:
    strip:
      _target_: ().strip()
