# examples/basic_features.yaml
feature_a:
  description: "Raw feature A"
  data_type: "float32"

feature_b:
  description: "Raw feature B"
  data_type: "float32"
  transformation:
    scale_feature:
      _target_: feature_fabrica.transform.ScaleFeature
      factor: 2

feature_d:
  description: "Derived feature D"
  data_type: "float32"
  dependencies: ["feature_a"]
  transformation:
    sum_fn:
      _target_: feature_fabrica.transform.SumReduce
      iterable: ["feature_a", 2]
    multiply:
      _target_: feature_fabrica.transform.DivideTransform
      numerator: 2

feature_c:
  description: "Derived feature C"
  data_type: "float32"
  dependencies: ["feature_a", "feature_b"]
  transformation:
    sum_fn:
      _target_: feature_fabrica.transform.SumReduce
      iterable: ["feature_a", "feature_b"]
    scale_feature:
      _target_: feature_fabrica.transform.ScaleFeature
      factor: "feature_a"

feature_e:
  description: "Raw feature E"
  data_type: "int32"
  transformation:
    one_hot:
      _target_: feature_fabrica.transform.LabelEncode
      categories: ["apple", "orange"]
