defaults:
  - _self_
  - basic_features

feature_z:
  description: "Value of feature E uppercased"
  data_type: "float32"
  dependencies: ["feature_d"]
  transformation:
    _target_: feature_d:scale + 2

feature_e_upper_then_lower:
  description: "Value of feature E uppercased"
  data_type: "str_"
  dependencies: ["feature_e"]
  transformation:
    import:
      _target_: (feature_e:upper).lower()

feature_e_upper_lower:
  description: "Value of feature E concatenated with upper, lower and original"
  data_type: "str_"
  dependencies: ["feature_e"]
  transformation:
    _target_: (feature_e:upper, feature_e:lower).concat(axis=0)
