defaults:
  - _self_
  - basic_features

feature_e_upper_then_lower:
  description: "Value of feature E uppercased"
  data_type: "str_"
  dependencies: ["feature_e"]
  transformation:
    import:
      _target_: (feature_e:upper).lower()

feature_e_upper_lower_original:
  description: "Value of feature E concatenated with upper, lower and original"
  data_type: "str_"
  dependencies: ["feature_e"]
  transformation:
    _target_: (feature_e:upper, feature_e:lower, feature_e).concat(expects_data=True, axis=0)
