defaults:
  - _self_
  - basic_features

sum_ab_divide_sum_ab:
  description: "(a + b) / (a + b)"
  data_type: "float32"
  dependencies: ["feature_a", "feature_b"]
  transformation:
    solve:
      _target_: (feature_a + feature_b) / (feature_a + feature_b)

a_multiple_b2:
  description: "a * b * 2"
  data_type: "float32"
  dependencies: ["feature_a", "feature_b"]
  transformation:
    solve:
      _target_: feature_a * feature_b

sum_ab2_divide_sum_ab:
  description: "(a + b) * 2 / (a + b)"
  data_type: "float32"
  dependencies: ["feature_a", "feature_b"]
  transformation:
    solve:
      _target_: ((feature_a + feature_b) * 2)/ (feature_a + feature_b)

sum_square_divide_sum:
  description: "((a + b) * (a + b)) / (a + b)"
  data_type: "float32"
  dependencies: ["feature_a", "feature_b"]
  transformation:
    solve:
      _target_: ((feature_a + feature_b) * (feature_a + feature_b))/ (feature_a + feature_b)
